//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.27130.2010
// 
namespace Client.ReportsEngineServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportsEngineServiceReference.IReportsEngineService")]
    public interface IReportsEngineService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportsEngineService/MostValuableClients", ReplyAction="http://tempuri.org/IReportsEngineService/MostValuableClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> MostValuableClientsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportsEngineService/MostCallingToCenterClients", ReplyAction="http://tempuri.org/IReportsEngineService/MostCallingToCenterClientsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> MostCallingToCenterClientsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportsEngineServiceChannel : Client.ReportsEngineServiceReference.IReportsEngineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportsEngineServiceClient : System.ServiceModel.ClientBase<Client.ReportsEngineServiceReference.IReportsEngineService>, Client.ReportsEngineServiceReference.IReportsEngineService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReportsEngineServiceClient() : 
                base(ReportsEngineServiceClient.GetDefaultBinding(), ReportsEngineServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IReportsEngineService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportsEngineServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReportsEngineServiceClient.GetBindingForEndpoint(endpointConfiguration), ReportsEngineServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportsEngineServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReportsEngineServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportsEngineServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReportsEngineServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReportsEngineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> MostValuableClientsAsync() {
            return base.Channel.MostValuableClientsAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> MostCallingToCenterClientsAsync() {
            return base.Channel.MostCallingToCenterClientsAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReportsEngineService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IReportsEngineService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:61783/Services/ReportsEngineService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return ReportsEngineServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IReportsEngineService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return ReportsEngineServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IReportsEngineService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IReportsEngineService,
        }
    }
}
